# Generated by Django 5.0.2 on 2024-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hockey',
            name='goals_against',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='goals_for',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='ot_losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='plus_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='win_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hockey',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
